server:
  tomcat:
    uri-encoding: UTF-8
  port: 8890
spring:
  devtools:
    restart:
      enabled: true
      # 下面这两个参数 解决了热部署后接口调用失败404的问题
      poll-interval: 3000ms
      quiet-period: 2999ms
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/modules_proj?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8    #这里serverTimezone必须配置，否则报错
    username: ENC(ijJa/eUVOk3i4TzdvbmlaQ==)
    password: ENC(RrPBXq12G2ocW75507sYaA==)
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
# 加密工具配置密钥
jasypt:
  encryptor:
    password: jasonwe


